"""Change time column type to String

Revision ID: 36d25730c687
Revises: a47f0993da6f
Create Date: 2025-05-25 20:27:48.019920

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '36d25730c687'
down_revision = 'a47f0993da6f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hot', schema=None) as batch_op:
        batch_op.alter_column('time',
               existing_type=mysql.INTEGER(),
               type_=sa.String(length=5),
               existing_nullable=True)

    with op.batch_alter_table('new', schema=None) as batch_op:
        batch_op.alter_column('time',
               existing_type=mysql.INTEGER(),
               type_=sa.String(length=5),
               existing_nullable=True)

    with op.batch_alter_table('original', schema=None) as batch_op:
        batch_op.alter_column('time',
               existing_type=mysql.INTEGER(),
               type_=sa.String(length=5),
               existing_nullable=True)

    with op.batch_alter_table('up', schema=None) as batch_op:
        batch_op.alter_column('time',
               existing_type=mysql.INTEGER(),
               type_=sa.String(length=5),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('up', schema=None) as batch_op:
        batch_op.alter_column('time',
               existing_type=sa.String(length=5),
               type_=mysql.INTEGER(),
               existing_nullable=True)

    with op.batch_alter_table('original', schema=None) as batch_op:
        batch_op.alter_column('time',
               existing_type=sa.String(length=5),
               type_=mysql.INTEGER(),
               existing_nullable=True)

    with op.batch_alter_table('new', schema=None) as batch_op:
        batch_op.alter_column('time',
               existing_type=sa.String(length=5),
               type_=mysql.INTEGER(),
               existing_nullable=True)

    with op.batch_alter_table('hot', schema=None) as batch_op:
        batch_op.alter_column('time',
               existing_type=sa.String(length=5),
               type_=mysql.INTEGER(),
               existing_nullable=True)

    # ### end Alembic commands ###
