"""empty message

Revision ID: a38d042b57f2
Revises: 36d25730c687
Create Date: 2025-05-25 22:03:47.379066

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a38d042b57f2'
down_revision = '36d25730c687'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chord_and_key_analysis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('song_id', sa.Integer(), nullable=True),
    sa.Column('chord_info', sa.Text(), nullable=True),
    sa.Column('key_analysis', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['song_id'], ['songs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chord_and_key_analysis')
    # ### end Alembic commands ###
