"""Change album to release and key to integer

Revision ID: a47f0993da6f
Revises: 4b045941e115
Create Date: 2025-05-25 19:13:17.055975

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a47f0993da6f'
down_revision = '4b045941e115'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('songs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('release', sa.String(length=100), nullable=True))
        batch_op.alter_column('key',
               existing_type=mysql.VARCHAR(length=20),
               type_=sa.Integer(),
               existing_nullable=True)
        batch_op.drop_column('album')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('songs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('album', mysql.VARCHAR(length=100), nullable=True))
        batch_op.alter_column('key',
               existing_type=sa.Integer(),
               type_=mysql.VARCHAR(length=20),
               existing_nullable=True)
        batch_op.drop_column('release')

    # ### end Alembic commands ###
